name: syncwatch
description: Synchronized local movie watching with integrated voice and video calls.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_selector: ^1.0.3
  http: ^1.6.0
  path: ^1.9.1
  livekit_client: ^2.13.0
  shared_preferences: ^2.5.3
  window_manager: ^0.5.2
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  media_kit: ^1.2.6
  multiview_desktop:
    git:
      url: https://github.com/vvlad-islavs/multi-view-desktop.git
      ref: f18498fe5257ab6e8291d86cbbbce2a2139b4fb7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
