class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'movies': 'Movies',
      'settings': 'Settings',
      'folder': 'Movie folder',
      'browse': 'Browse...',
      'room': 'Room',
      'friendOnline': 'Friend online',
      'open': 'Open',
      'duration': 'Duration',
      'resolution': 'Resolution',
      'audioTracks': 'Audio tracks',
      'subtitles': 'Subtitles',
      'playback': 'Playback',
      'call': 'Call',
      'audio': 'Audio',
      'video': 'Video',
      'sync': 'Sync',
      'language': 'Language',
      'skipInterval': 'Skip interval',
      'seconds': 'seconds',
      'autoReady': 'Automatically ready when media is loaded',
      'ducking': 'Lower movie volume while someone is speaking',
      'cameraQuality': 'Camera quality',
      'movieVolume': 'Movie',
      'callVolume': 'Call',
      'server': 'Server',
      'username': 'Username',
      'back': 'Back',
      'connected': 'Connected',
      'ready': 'READY',
      'minimize': 'Minimize',
      'fullscreen': 'Fullscreen',
      'hide': 'Hide',
      'restore': 'Restore video',
      'mockMode': 'Mock mode',
      'movieLibrary': 'My library',
      'scanSubfolders': 'Scan subfolders',
      'interface': 'Interface',
      'selectedMovie': 'Selected movie',
      'startWatching': 'Start watching',
      'searchFiles': 'Search files...',
      'fileLocation': 'File location',
      'roomStatus': 'Watch room',
      'bothReady': '2 / 2 ready',
      'save': 'Save',
      'cancel': 'Cancel',
      'general': 'General',
      'advanced': 'Advanced',
      'automaticRefresh': 'Refresh library automatically',
      'moviesHint': 'Choose where your local movie files are stored.',
    },
    'ru': {
      'movies': 'Фильмы',
      'settings': 'Настройки',
      'folder': 'Папка с фильмами',
      'browse': 'Обзор...',
      'room': 'Комната',
      'friendOnline': 'Друг онлайн',
      'open': 'Открыть',
      'duration': 'Длительность',
      'resolution': 'Разрешение',
      'audioTracks': 'Аудиодорожки',
      'subtitles': 'Субтитры',
      'playback': 'Воспроизведение',
      'call': 'Звонок',
      'audio': 'Звук',
      'video': 'Видео',
      'sync': 'Синхронизация',
      'language': 'Язык',
      'skipInterval': 'Шаг перемотки',
      'seconds': 'секунд',
      'autoReady': 'Автоматически ставить «Готов» после загрузки фильма',
      'ducking': 'Приглушать фильм, когда собеседник говорит',
      'cameraQuality': 'Качество камеры',
      'movieVolume': 'Фильм',
      'callVolume': 'Звонок',
      'server': 'Сервер',
      'username': 'Имя',
      'back': 'Назад',
      'connected': 'Подключено',
      'ready': 'ГОТОВ',
      'minimize': 'Свернуть',
      'fullscreen': 'На весь экран',
      'hide': 'Скрыть',
      'restore': 'Вернуть видео',
      'mockMode': 'Демо-режим',
      'movieLibrary': 'Моя библиотека',
      'scanSubfolders': 'Сканировать подпапки',
      'interface': 'Интерфейс',
      'selectedMovie': 'Выбранный фильм',
      'startWatching': 'Начать просмотр',
      'searchFiles': 'Поиск по файлам...',
      'fileLocation': 'Расположение файла',
      'roomStatus': 'Комната просмотра',
      'bothReady': '2 / 2 готовы',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'general': 'Общие',
      'advanced': 'Дополнительно',
      'automaticRefresh': 'Автоматически обновлять библиотеку',
      'moviesHint': 'Укажите, где хранятся локальные файлы фильмов.',
    },
  };

  static String get(String languageCode, String key) {
    return _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}
