class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'movies': 'Movies',
      'settings': 'Settings',
      'folder': 'Movie folder',
      'browse': 'Browse...',
      'room': 'Room',
      'friendOnline': 'Partner online',
      'open': 'Open',
      'openAudioTrack': 'Audio track…',
      'openSubtitles': 'Subtitles…',
      'duration': 'Duration',
      'resolution': 'Resolution',
      'audioTracks': 'Audio tracks',
      'subtitles': 'Subtitles',
      'playback': 'Playback',
      'call': 'Call',
      'audio': 'Audio',
      'video': 'Video',
      'sync': 'Connection',
      'language': 'Language',
      'skipInterval': 'Skip interval',
      'seconds': 'seconds',
      'secondsShort': 's',
      'autoReady': 'Automatically ready when media is loaded',
      'timelinePreview': 'Show frame preview when hovering the timeline',
      'playerSettings': 'Player settings',
      'subtitleSize': 'Subtitle size',
      'subtitlePosition': 'Subtitle position',
      'subtitlePositionTop': 'Top',
      'subtitlePositionHigher': 'Higher',
      'subtitlePositionNormal': 'Normal',
      'subtitlePositionLower': 'Lower',
      'subtitlePositionBottom': 'Bottom',
      'subtitleVerticalOffset': 'Vertical offset',
      'resetSection': 'Reset section',
      'subtitleFont': 'Font',
      'subtitleTextColor': 'Text color',
      'subtitleOutlineColor': 'Outline color',
      'subtitleOutlineWidth': 'Outline width',
      'subtitleEdgePadding': 'Edge padding',
      'videoImage': 'Image',
      'brightness': 'Brightness',
      'contrast': 'Contrast',
      'saturation': 'Saturation',
      'hue': 'Hue',
      'defaultVolume': 'Default volume',
      'rememberVolume': 'Remember volume between sessions',
      'normalizeAudio': 'Normalize audio',
      'advancedPlayer': 'Advanced',
      'smoothScaling': 'Smooth scaling',
      'hideCursorFullscreen': 'Hide cursor in fullscreen',
      'previewCache': 'Preview frame cache',
      'ducking': 'Lower movie volume while someone is speaking',
      'cameraQuality': 'Camera quality',
      'inputDevice': 'Microphone',
      'outputDevice': 'Audio output',
      'systemDefault': 'System default',
      'laptopMicrophone': 'Laptop microphone',
      'usbMicrophone': 'USB microphone',
      'speakers': 'Speakers',
      'headphones': 'Headphones',
      'movieVolume': 'Movie',
      'callVolume': 'Call',
      'server': 'Server',
      'username': 'Username',
      'back': 'Back',
      'connected': 'Connected',
      'ready': 'READY',
      'notReady': 'Not ready',
      'minimize': 'Minimize',
      'fullscreen': 'Fullscreen',
      'hide': 'Hide',
      'restore': 'Restore video',
      'mockMode': 'Mock mode',
      'movieLibrary': 'My library',
      'scanSubfolders': 'Scan subfolders',
      'interface': 'Interface',
      'selectedMovie': 'Selected movie',
      'startWatching': 'Start watching',
      'continueWatching': 'Continue watching',
      'searchFiles': 'Search files...',
      'fileLocation': 'File location',
      'roomStatus': 'Watch room',
      'bothReady': '2 / 2 ready',
      'save': 'Save',
      'changesSaved': 'Changes saved',
      'cancel': 'Cancel',
      'general': 'General',
      'advanced': 'Advanced',
      'automaticRefresh': 'Refresh library automatically',
      'moviesHint': 'Choose where your local movie files are stored.',
      'appearanceHint': 'SyncWatch desktop appearance and language.',
      'playbackHint': 'Playback behaviour and synchronization preferences.',
      'callHint': 'Camera and call audio preferences.',
      'syncHint': 'Server, room and identity used to connect.',
      'files': 'files',
      'recentActivity': 'Recent activity',
      'friendJoined': 'Partner joined the room',
      'friendReady': 'Partner is ready',
      'movieSelected': 'Movie selected',
      'you': 'You',
      'friend': 'Partner',
      'waiting': 'Waiting',
      'unknown': '—',
      'noMovies': 'No supported video files found in this folder.',
      'rescan': 'Rescan',
      'defaultAudio': 'Default audio',
      'subtitlesOff': 'None',
      'startCall': 'Start call',
      'goToCall': 'Go to call',
      'endCall': 'End call',
      'callActive': 'Call active',
      'callInactive': 'Call not started',
      'cameraOn': 'Camera on',
      'microphoneOn': 'Microphone on',
      'microphoneOff': 'Microphone off',
      'cameraOff': 'Camera off',
      'microphone': 'Microphone',
      'partnerVideo': 'Partner',
      'play': 'Play',
      'pause': 'Pause',
      'muteMovie': 'Mute movie',
      'unmuteMovie': 'Unmute movie',
      'noAudioTracks': 'No audio tracks',
      'noSubtitles': 'None',
      'audioTrack': 'Audio track',
      'subtitleTrack': 'Subtitle track',
      'playlist': 'Playlist',
      'previousFile': 'Previous file',
      'nextFile': 'Next file',
    },
    'ru': {
      'movies': 'Фильмы',
      'settings': 'Настройки',
      'folder': 'Папка с фильмами',
      'browse': 'Обзор...',
      'room': 'Комната',
      'friendOnline': 'Собеседник онлайн',
      'open': 'Открыть',
      'openAudioTrack': 'Аудиодорожку…',
      'openSubtitles': 'Субтитры…',
      'duration': 'Длительность',
      'resolution': 'Разрешение',
      'audioTracks': 'Аудиодорожки',
      'subtitles': 'Субтитры',
      'playback': 'Воспроизведение',
      'call': 'Звонок',
      'audio': 'Звук',
      'video': 'Видео',
      'sync': 'Подключение',
      'language': 'Язык',
      'skipInterval': 'Шаг перемотки',
      'seconds': 'секунд',
      'secondsShort': 'с',
      'autoReady': 'Автоматически ставить «Готов» после загрузки фильма',
      'timelinePreview': 'Показывать кадр при наведении на шкалу',
      'playerSettings': 'Настройки плеера',
      'subtitleSize': 'Размер субтитров',
      'subtitlePosition': 'Положение субтитров',
      'subtitlePositionTop': 'Сверху',
      'subtitlePositionHigher': 'Выше',
      'subtitlePositionNormal': 'Обычно',
      'subtitlePositionLower': 'Ниже',
      'subtitlePositionBottom': 'Внизу',
      'subtitleVerticalOffset': 'Смещение по вертикали',
      'resetSection': 'Сбросить раздел',
      'subtitleFont': 'Шрифт',
      'subtitleTextColor': 'Цвет текста',
      'subtitleOutlineColor': 'Цвет обводки',
      'subtitleOutlineWidth': 'Толщина обводки',
      'subtitleEdgePadding': 'Отступ от края',
      'videoImage': 'Изображение',
      'brightness': 'Яркость',
      'contrast': 'Контрастность',
      'saturation': 'Насыщенность',
      'hue': 'Оттенок',
      'defaultVolume': 'Громкость по умолчанию',
      'rememberVolume': 'Запоминать громкость между сеансами',
      'normalizeAudio': 'Нормализация громкости',
      'advancedPlayer': 'Дополнительно',
      'smoothScaling': 'Плавное масштабирование',
      'hideCursorFullscreen': 'Скрывать курсор в полноэкранном режиме',
      'previewCache': 'Кэш кадров предпросмотра',
      'ducking': 'Приглушать фильм, когда собеседник говорит',
      'cameraQuality': 'Качество камеры',
      'inputDevice': 'Микрофон',
      'outputDevice': 'Выход звука',
      'systemDefault': 'Системный по умолчанию',
      'laptopMicrophone': 'Микрофон ноутбука',
      'usbMicrophone': 'USB-микрофон',
      'speakers': 'Динамики',
      'headphones': 'Наушники',
      'movieVolume': 'Фильм',
      'callVolume': 'Звонок',
      'server': 'Сервер',
      'username': 'Имя',
      'back': 'Назад',
      'connected': 'Подключено',
      'ready': 'ГОТОВ',
      'notReady': 'Не готов',
      'minimize': 'Свернуть',
      'fullscreen': 'На весь экран',
      'hide': 'Скрыть',
      'restore': 'Вернуть видео',
      'mockMode': 'Демо-режим',
      'movieLibrary': 'Моя библиотека',
      'scanSubfolders': 'Сканировать подпапки',
      'interface': 'Интерфейс',
      'selectedMovie': 'Выбранный фильм',
      'startWatching': 'Начать просмотр',
      'continueWatching': 'Продолжить просмотр',
      'searchFiles': 'Поиск по файлам...',
      'fileLocation': 'Расположение файла',
      'roomStatus': 'Комната просмотра',
      'bothReady': '2 / 2 готовы',
      'save': 'Сохранить',
      'changesSaved': 'Изменения сохранены',
      'cancel': 'Отмена',
      'general': 'Общие',
      'advanced': 'Дополнительно',
      'automaticRefresh': 'Автоматически обновлять библиотеку',
      'moviesHint': 'Укажите, где хранятся локальные файлы фильмов.',
      'appearanceHint': 'Внешний вид SyncWatch и язык интерфейса.',
      'playbackHint': 'Поведение плеера и параметры синхронизации.',
      'callHint': 'Камера, микрофон и параметры звука звонка.',
      'syncHint': 'Сервер, комната и имя для подключения.',
      'files': 'файлов',
      'recentActivity': 'Последняя активность',
      'friendJoined': 'Собеседник подключился к комнате',
      'friendReady': 'Собеседник готов к просмотру',
      'movieSelected': 'Фильм выбран',
      'you': 'Вы',
      'friend': 'Собеседник',
      'waiting': 'Ожидание',
      'unknown': '—',
      'noMovies': 'В этой папке не найдено поддерживаемых видеофайлов.',
      'rescan': 'Пересканировать',
      'defaultAudio': 'Аудио по умолчанию',
      'subtitlesOff': 'Нет',
      'startCall': 'Начать звонок',
      'goToCall': 'Перейти к звонку',
      'endCall': 'Завершить звонок',
      'callActive': 'Звонок идёт',
      'callInactive': 'Звонок не начат',
      'cameraOn': 'Камера включена',
      'microphoneOn': 'Микрофон включён',
      'microphoneOff': 'Микрофон выключен',
      'cameraOff': 'Камера выключена',
      'microphone': 'Микрофон',
      'partnerVideo': 'Собеседник',
      'play': 'Воспроизвести',
      'pause': 'Пауза',
      'muteMovie': 'Выключить звук фильма',
      'unmuteMovie': 'Включить звук фильма',
      'noAudioTracks': 'Нет аудиодорожек',
      'noSubtitles': 'Нет',
      'audioTrack': 'Аудиодорожка',
      'subtitleTrack': 'Субтитры',
      'playlist': 'Плейлист',
      'previousFile': 'Предыдущий файл',
      'nextFile': 'Следующий файл',
    },
  };

  static String get(String languageCode, String key) {
    return _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}
