$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $root '.dart_tool\package_config.json'
if (!(Test-Path $configPath)) { throw 'Run flutter pub get first.' }
$packages = (Get-Content $configPath -Raw | ConvertFrom-Json).packages
$overridePath = Join-Path $root 'pubspec_overrides.yaml'
$marker = '# Generated by scripts/prepare_native_plugins.ps1'
if (Test-Path $overridePath) {
  $existing = Get-Content $overridePath -Raw
  if (!$existing.StartsWith($marker) -and
      !$existing.StartsWith('# Generated by scripts/prepare_webrtc_plugin.ps1')) {
    throw 'Existing pubspec_overrides.yaml is user-owned; merge the isolated native plugin overrides manually.'
  }
}
$overrides = @{}
foreach ($entry in @(
  @{name = 'flutter_webrtc'; patch = 'flutter-webrtc-remote-media-lock.patch'},
  @{name = 'media_kit_video'; patch = 'media-kit-windows-resize-leak.patch'}
)) {
  $dependency = $packages | Where-Object name -eq $entry.name | Select-Object -First 1
  if (!$dependency) { throw "$($entry.name) is absent from package_config.json." }
  $source = ([Uri]::new([Uri]::new($configPath), $dependency.rootUri)).LocalPath
  $relative = ".dart_tool/syncwatch_plugins/$($entry.name)"
  $destination = Join-Path $root $relative
  if (!(Test-Path $destination)) {
    New-Item (Split-Path $destination -Parent) -ItemType Directory -Force | Out-Null
    Copy-Item $source $destination -Recurse
  }
  $patch = Join-Path $root "patches\$($entry.patch)"
  Push-Location $destination
  try {
    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    & git apply --reverse --check $patch 2>$null
    $alreadyApplied = $LASTEXITCODE -eq 0
    $ErrorActionPreference = $previousPreference
    if (!$alreadyApplied) {
      & git apply --check $patch
      if ($LASTEXITCODE -ne 0) { throw "$($entry.name) source changed; review its native patch before building." }
      & git apply $patch
      if ($LASTEXITCODE -ne 0) { throw 'Applying the native patch failed.' }
    }
  } finally {
    $ErrorActionPreference = $previousPreference
    Pop-Location
  }
  $overrides[$entry.name] = @{path = $relative}
}
$settings = @{dependency_overrides = $overrides}
$text = $marker + "`n" + ($settings | ConvertTo-Json -Depth 4) + "`n"
[IO.File]::WriteAllText($overridePath, $text, [Text.UTF8Encoding]::new($false))
Write-Host 'Prepared isolated native plugins. Run flutter pub get again before building.'
