import 'dart:convert';
import 'dart:io';

const _override = '''# Generated by scripts/prepare_image.dart
dependency_overrides:
  image:
    path: .dart_tool/syncwatch_plugins/image
''';

Future<void> main(List<String> arguments) async {
  if (arguments.any(
    (argument) =>
        argument != '--use-resolved-package' && argument != '--prepare-only',
  )) {
    stderr.writeln(
      'Run: dart run scripts/prepare_image.dart '
      '[--use-resolved-package] [--prepare-only]',
    );
    exitCode = 64;
    return;
  }
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final config = File('${root.path}/.dart_tool/package_config.json');
  if (!config.existsSync()) {
    throw StateError('Run flutter pub get first.');
  }
  final packages =
      (jsonDecode(await config.readAsString())
              as Map<String, dynamic>)['packages']
          as List<dynamic>;
  final package = packages.cast<Map<String, dynamic>>().firstWhere(
    (package) => package['name'] == 'image',
  );
  final source = Directory.fromUri(
    config.uri.resolve(package['rootUri'] as String),
  );
  final useResolved = arguments.contains('--use-resolved-package');
  final prepareOnly = arguments.contains('--prepare-only');
  final overrideFile = File('${root.path}/pubspec_overrides.yaml');
  if (!useResolved && !prepareOnly && overrideFile.existsSync()) {
    final existing = (await overrideFile.readAsString()).replaceAll(
      '\r\n',
      '\n',
    );
    if (existing != _override) {
      throw StateError(
        'Preserving existing pubspec_overrides.yaml. Select an isolated '
        '.dart_tool dependency and use --use-resolved-package, or merge '
        'the override manually.',
      );
    }
  }
  final destination = useResolved
      ? source
      : Directory('${root.path}/.dart_tool/syncwatch_plugins/image');
  final isolatedRoot = Directory(
    '${root.path}/.dart_tool',
  ).resolveSymbolicLinksSync();
  if (destination.existsSync() &&
      !_isWithin(isolatedRoot, destination.resolveSymbolicLinksSync())) {
    throw StateError(
      'The dependency must be inside this checkout\'s .dart_tool.',
    );
  }
  if (!destination.existsSync()) {
    await destination.parent.create(recursive: true);
    if (!_isWithin(
      isolatedRoot,
      destination.parent.resolveSymbolicLinksSync(),
    )) {
      throw StateError('Refusing a dependency directory outside .dart_tool.');
    }
    final staging = await destination.parent.createTemp('image.preparing-');
    await _copy(source, staging);
    await staging.rename(destination.path);
  }
  final pubspec = await File('${destination.path}/pubspec.yaml').readAsString();
  if (!RegExp(r'^version: 4\.10\.1\s*$', multiLine: true).hasMatch(pubspec)) {
    throw StateError('Review the image patches for this package version.');
  }
  final patches = [
    'image-jpeg-typed-dct.patch',
    'image-jpeg-bitwriter.patch',
    'image-jpeg-rgb-read.patch',
  ].map((name) => '${root.path}/patches/$name').toList();
  await _applyPatches(destination, patches);
  if (!useResolved && !prepareOnly) {
    await overrideFile.writeAsString(_override);
  }
  stdout.writeln('Prepared isolated image package. Run flutter pub get next.');
}

Future<void> _applyPatches(Directory destination, List<String> patches) async {
  // All image patches target this file. Later patches can change the context
  // of earlier ones, so verify the stack in reverse order in a temporary copy.
  const relativePath = 'lib/src/formats/jpeg_encoder.dart';
  final source = File('${destination.path}/$relativePath');
  final staging = await destination.parent.createTemp('image.patching-');
  try {
    final staged = File('${staging.path}/$relativePath');
    await staged.parent.create(recursive: true);
    await source.copy(staged.path);
    for (final patch in patches.reversed) {
      final check = await Process.run('git', [
        'apply',
        '--reverse',
        '--check',
        patch,
      ], workingDirectory: staging.path);
      if (check.exitCode == 0) {
        final result = await Process.run('git', [
          'apply',
          '--reverse',
          patch,
        ], workingDirectory: staging.path);
        if (result.exitCode != 0) {
          throw StateError(
            'Checking image patch $patch failed. ${result.stderr}',
          );
        }
      }
    }
    for (final patch in patches) {
      await _applyPatch(staging, patch);
    }
    // Do not modify the resolved dependency until the entire stack passes.
    await staged.copy(source.path);
  } finally {
    await staging.delete(recursive: true);
  }
}

Future<void> _applyPatch(Directory destination, String patch) async {
  Future<ProcessResult> git(List<String> arguments) => Process.run('git', [
    'apply',
    ...arguments,
    patch,
  ], workingDirectory: destination.path);
  final applied = await git(['--reverse', '--check']);
  if (applied.exitCode != 0) {
    final check = await git(['--check']);
    if (check.exitCode != 0) {
      throw StateError(
        'Image source changed; review compatibility. ${check.stderr}',
      );
    }
    final result = await git([]);
    if (result.exitCode != 0) {
      throw StateError('Applying image patch $patch failed. ${result.stderr}');
    }
  }
}

Future<void> _copy(Directory source, Directory destination) async {
  await for (final entry in source.list(followLinks: false)) {
    final name = entry.uri.pathSegments
        .where((segment) => segment.isNotEmpty)
        .last;
    final target = '${destination.path}/$name';
    if (entry is Link) {
      await Link(target).create(await entry.target());
    } else if (entry is Directory) {
      await _copy(entry, await Directory(target).create());
    } else if (entry is File) {
      await entry.copy(target);
    }
  }
}

bool _isWithin(String root, String child) {
  if (Platform.isWindows) {
    root = root.toLowerCase();
    child = child.toLowerCase();
  }
  final prefix = root.endsWith(Platform.pathSeparator)
      ? root
      : '$root${Platform.pathSeparator}';
  return child.startsWith(prefix);
}
