param([switch]$UseResolvedPlugin)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $root '.dart_tool\package_config.json'
if (!(Test-Path $configPath)) { throw 'Run flutter pub get first.' }
$packages = (Get-Content $configPath -Raw | ConvertFrom-Json).packages
$dependency = $packages | Where-Object name -eq 'flutter_webrtc'
if (!$dependency) { throw 'flutter_webrtc is absent from package_config.json.' }
$source = ([Uri]::new([Uri]::new($configPath), $dependency.rootUri)).LocalPath
$destination = Join-Path $root '.dart_tool\syncwatch_plugins\flutter_webrtc'
$overridePath = Join-Path $root 'pubspec_overrides.yaml'
$marker = '# Generated by scripts/prepare_webrtc_plugin.ps1'
if ($UseResolvedPlugin) {
  # An explicitly selected, already isolated dependency needs no YAML changes.
  $isolatedRoot = [IO.Path]::GetFullPath((Join-Path $root '.dart_tool')) + '\'
  if (![IO.Path]::GetFullPath($source).StartsWith($isolatedRoot, [StringComparison]::OrdinalIgnoreCase)) {
    throw '-UseResolvedPlugin requires a dependency inside this checkout''s .dart_tool directory.'
  }
  $destination = $source
} elseif (Test-Path $overridePath) {
  $expected = $marker + "`n" + "dependency_overrides:`n  flutter_webrtc:`n    path: .dart_tool/syncwatch_plugins/flutter_webrtc`n"
  $withVideo = $expected + "  media_kit_video:`n    path: .dart_tool/syncwatch_plugins/media_kit_video`n"
  $withMedia = $withVideo + "  media_kit:`n    path: .dart_tool/syncwatch_plugins/media_kit`n"
  $withImage = $withMedia + "  image:`n    path: .dart_tool/syncwatch_plugins/image`n"
  $withLiveKit = $withImage + "  livekit_client:`n    path: .dart_tool/syncwatch_plugins/livekit_client`n"
  $existing = (Get-Content $overridePath -Raw).Replace("`r`n", "`n")
  if ($existing -ne $expected -and $existing -ne $withVideo -and $existing -ne $withMedia -and $existing -ne $withImage -and $existing -ne $withLiveKit) {
    throw 'Preserving existing pubspec_overrides.yaml. Select an isolated .dart_tool dependency and use -UseResolvedPlugin, or merge its override manually.'
  }
}
if (!(Test-Path $destination)) {
  New-Item (Split-Path $destination -Parent) -ItemType Directory -Force | Out-Null
  # PowerShell 5.1 Copy-Item cannot handle long paths in package examples.
  # Publish the copy only after robocopy has completed successfully.
  $staging = $destination + '.preparing-' + [Guid]::NewGuid().ToString('N')
  & robocopy $source $staging /E /R:1 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
  if ($LASTEXITCODE -ge 8) { throw "Dependency copy failed; inspect $staging" }
  Move-Item $staging $destination
}
if (!(Select-String -Path (Join-Path $destination 'pubspec.yaml') -Pattern '^version: 1\.6\.2\+hotfix\.3\s*$' -Quiet)) {
  throw 'Review the native patch before using a different flutter_webrtc version.'
}
$patch = Join-Path $root 'patches\flutter-webrtc-remote-media-lifetime.patch'
Push-Location $destination
try {
  $previousPreference = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  & git apply --reverse --check $patch 2>$null
  $alreadyApplied = $LASTEXITCODE -eq 0
  $ErrorActionPreference = $previousPreference
  if (!$alreadyApplied) {
    & git apply --check $patch
    if ($LASTEXITCODE -ne 0) { throw 'WebRTC source changed; review patch compatibility.' }
    & git apply $patch
    if ($LASTEXITCODE -ne 0) { throw 'Applying the native WebRTC patch failed.' }
  }
  Copy-Item (Join-Path $root 'tools\webrtc\remote_media_cache.h') (Join-Path $destination 'common\cpp\include\syncwatch_remote_media_cache.h') -Force
} finally {
  $ErrorActionPreference = $previousPreference
  Pop-Location
}
# Prepare the video renderer in the same isolated dependency area. The native
# patch removes an unused GL binding that otherwise retains resized pbuffers.
$videoDependency = $packages | Where-Object name -eq 'media_kit_video'
if (!$videoDependency) { throw 'media_kit_video is absent from package_config.json.' }
$videoSource = ([Uri]::new([Uri]::new($configPath), $videoDependency.rootUri)).LocalPath
$videoDestination = Join-Path $root '.dart_tool\syncwatch_plugins\media_kit_video'
if ($UseResolvedPlugin) {
  if (![IO.Path]::GetFullPath($videoSource).StartsWith($isolatedRoot, [StringComparison]::OrdinalIgnoreCase)) {
    throw '-UseResolvedPlugin requires media_kit_video inside this checkout''s .dart_tool directory.'
  }
  $videoDestination = $videoSource
}
if (!(Test-Path $videoDestination)) {
  $staging = $videoDestination + '.preparing-' + [Guid]::NewGuid().ToString('N')
  & robocopy $videoSource $staging /E /R:1 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
  if ($LASTEXITCODE -ge 8) { throw "Dependency copy failed; inspect $staging" }
  Move-Item $staging $videoDestination
}
if (!(Select-String -Path (Join-Path $videoDestination 'pubspec.yaml') -Pattern '^version: 2\.0\.1\s*$' -Quiet)) {
  throw 'Review the surface-lifetime patch before using a different media_kit_video version.'
}
$videoPatch = Join-Path $root 'patches\media-kit-video-surface-lifetime.patch'
Push-Location $videoDestination
try {
  $previousPreference = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  & git apply --reverse --check $videoPatch 2>$null
  $alreadyApplied = $LASTEXITCODE -eq 0
  $ErrorActionPreference = $previousPreference
  if (!$alreadyApplied) {
    & git apply --check $videoPatch
    if ($LASTEXITCODE -ne 0) { throw 'Video source changed; review patch compatibility.' }
    & git apply $videoPatch
    if ($LASTEXITCODE -ne 0) { throw 'Applying the surface-lifetime patch failed.' }
  }
} finally {
  $ErrorActionPreference = $previousPreference
  Pop-Location
}
# Prepare the screenshot argument fix without replacing this helper's override.
$mediaArguments = @((Join-Path $root 'scripts\prepare_media_kit.dart'), '--prepare-only')
if ($UseResolvedPlugin) { $mediaArguments += '--use-resolved-package' }
& dart @mediaArguments
if ($LASTEXITCODE -ne 0) { throw 'Preparing media_kit failed.' }
$imageArguments = @((Join-Path $root 'scripts\prepare_image.dart'), '--prepare-only')
if ($UseResolvedPlugin) { $imageArguments += '--use-resolved-package' }
& dart @imageArguments
if ($LASTEXITCODE -ne 0) { throw 'Preparing image failed.' }
$livekitArguments = @((Join-Path $root 'scripts\prepare_livekit.dart'), '--prepare-only')
if ($UseResolvedPlugin) { $livekitArguments += '--use-resolved-package' }
& dart @livekitArguments
if ($LASTEXITCODE -ne 0) { throw 'Preparing LiveKit failed.' }
if (!$UseResolvedPlugin) {
  $text = $marker + "`n" + "dependency_overrides:`n  flutter_webrtc:`n    path: .dart_tool/syncwatch_plugins/flutter_webrtc`n  media_kit_video:`n    path: .dart_tool/syncwatch_plugins/media_kit_video`n  media_kit:`n    path: .dart_tool/syncwatch_plugins/media_kit`n"
  $text += "  image:`n    path: .dart_tool/syncwatch_plugins/image`n"
  $text += "  livekit_client:`n    path: .dart_tool/syncwatch_plugins/livekit_client`n"
  [IO.File]::WriteAllText($overridePath, $text, [Text.UTF8Encoding]::new($false))
}
Write-Host 'Prepared isolated WebRTC and video plugins. Run flutter pub get before building.'
