import 'dart:convert';
import 'dart:io';

const _previousOverride =
    '''# Generated by scripts/prepare_macos_video_plugin.dart
dependency_overrides:
  media_kit_video:
    path: .dart_tool/syncwatch_plugins/media_kit_video
''';
const _mediaOverride =
    '$_previousOverride  media_kit:\n'
    '    path: .dart_tool/syncwatch_plugins/media_kit\n';
const _override =
    '$_mediaOverride  image:\n'
    '    path: .dart_tool/syncwatch_plugins/image\n';

Future<void> main(List<String> arguments) async {
  if (!Platform.isMacOS ||
      arguments.any((argument) => argument != '--use-resolved-plugin')) {
    stderr.writeln(
      'Run on macOS: dart run scripts/prepare_macos_video_plugin.dart '
      '[--use-resolved-plugin]',
    );
    exitCode = 64;
    return;
  }
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final config = File('${root.path}/.dart_tool/package_config.json');
  if (!config.existsSync()) {
    throw StateError('Run flutter pub get first.');
  }
  final packages =
      (jsonDecode(await config.readAsString())
              as Map<String, dynamic>)['packages']
          as List<dynamic>;
  final package = packages.cast<Map<String, dynamic>>().firstWhere(
    (package) => package['name'] == 'media_kit_video',
  );
  final source = Directory.fromUri(
    config.uri.resolve(package['rootUri'] as String),
  );
  final useResolved = arguments.contains('--use-resolved-plugin');
  final overrideFile = File('${root.path}/pubspec_overrides.yaml');
  if (!useResolved && overrideFile.existsSync()) {
    final existing = (await overrideFile.readAsString()).replaceAll(
      '\r\n',
      '\n',
    );
    if (existing != _override &&
        existing != _mediaOverride &&
        existing != _previousOverride) {
      throw StateError(
        'Preserving existing pubspec_overrides.yaml. Select an isolated '
        '.dart_tool dependency and use --use-resolved-plugin, or merge '
        'the override manually.',
      );
    }
  }
  final destination = useResolved
      ? source
      : Directory('${root.path}/.dart_tool/syncwatch_plugins/media_kit_video');
  final isolatedRoot = Directory(
    '${root.path}/.dart_tool',
  ).resolveSymbolicLinksSync();
  if (destination.existsSync() &&
      !destination.resolveSymbolicLinksSync().startsWith('$isolatedRoot/')) {
    throw StateError(
      'The dependency must be inside this checkout\'s .dart_tool.',
    );
  }
  if (!destination.existsSync()) {
    await destination.parent.create(recursive: true);
    final staging = await destination.parent.createTemp(
      'media_kit_video.preparing-',
    );
    await _copy(source, staging);
    await staging.rename(destination.path);
  }
  final pubspec = await File('${destination.path}/pubspec.yaml').readAsString();
  if (!RegExp(r'^version: 2\.0\.1\s*$', multiLine: true).hasMatch(pubspec)) {
    throw StateError(
      'Review the texture-cache patch for this package version.',
    );
  }
  final patch =
      '${root.path}/patches/media-kit-video-macos-texture-cache.patch';
  Future<ProcessResult> git(List<String> arguments) => Process.run('git', [
    'apply',
    ...arguments,
    patch,
  ], workingDirectory: destination.path);
  final applied = await git(['--reverse', '--check']);
  if (applied.exitCode != 0) {
    final check = await git(['--check']);
    if (check.exitCode != 0) {
      throw StateError(
        'Video source changed; review compatibility. ${check.stderr}',
      );
    }
    final result = await git([]);
    if (result.exitCode != 0) {
      throw StateError(
        'Applying the texture-cache patch failed. ${result.stderr}',
      );
    }
  }
  final mediaResult = await Process.run(Platform.resolvedExecutable, [
    '${root.path}/scripts/prepare_media_kit.dart',
    '--prepare-only',
    if (useResolved) '--use-resolved-package',
  ]);
  if (mediaResult.exitCode != 0) {
    throw StateError('Preparing media_kit failed. ${mediaResult.stderr}');
  }
  final imageResult = await Process.run(Platform.resolvedExecutable, [
    '${root.path}/scripts/prepare_image.dart',
    '--prepare-only',
    if (useResolved) '--use-resolved-package',
  ]);
  if (imageResult.exitCode != 0) {
    throw StateError('Preparing image failed. ${imageResult.stderr}');
  }
  if (!useResolved) await overrideFile.writeAsString(_override);
  stdout.writeln('Prepared isolated video plugin. Run flutter pub get next.');
}

Future<void> _copy(Directory source, Directory destination) async {
  await for (final entry in source.list(followLinks: false)) {
    final name = entry.path.substring(
      source.path.replaceFirst(RegExp(r'/$'), '').length + 1,
    );
    final target = '${destination.path}/$name';
    if (entry is Link) {
      await Link(target).create(await entry.target());
    } else if (entry is Directory) {
      await _copy(entry, await Directory(target).create());
    } else if (entry is File) {
      await entry.copy(target);
    }
  }
}
