$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $root '.dart_tool\package_config.json'
if (!(Test-Path $configPath)) { throw 'Run flutter pub get first.' }
$packages = (Get-Content $configPath -Raw | ConvertFrom-Json).packages
$dependency = $packages | Where-Object name -eq 'flutter_webrtc'
if (!$dependency) { throw 'flutter_webrtc is absent from package_config.json.' }
$source = ([Uri]::new([Uri]::new($configPath), $dependency.rootUri)).LocalPath
$destination = Join-Path $root '.dart_tool\syncwatch_plugins\flutter_webrtc'
$overridePath = Join-Path $root 'pubspec_overrides.yaml'
$marker = '# Generated by scripts/prepare_webrtc_plugin.ps1'
if (Test-Path $overridePath) {
  if (!(Get-Content $overridePath -Raw).StartsWith($marker)) {
    throw 'Existing pubspec_overrides.yaml is user-owned; merge the isolated flutter_webrtc override manually.'
  }
}
if (!(Test-Path $destination)) {
  New-Item (Split-Path $destination -Parent) -ItemType Directory -Force | Out-Null
  Copy-Item $source $destination -Recurse
}
$patch = Join-Path $root 'patches\flutter-webrtc-remote-media-lock.patch'
Push-Location $destination
try {
  $previousPreference = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  & git apply --reverse --check $patch 2>$null
  $alreadyApplied = $LASTEXITCODE -eq 0
  $ErrorActionPreference = $previousPreference
  if (!$alreadyApplied) {
    & git apply --check $patch
    if ($LASTEXITCODE -ne 0) { throw 'WebRTC source changed; review the native patch before building.' }
    & git apply $patch
    if ($LASTEXITCODE -ne 0) { throw 'Applying the WebRTC native patch failed.' }
  }
} finally {
  if ($previousPreference) { $ErrorActionPreference = $previousPreference }
  Pop-Location
}
# JSON is valid YAML. Keep the override generated and the pub cache untouched.
$settings = @{dependency_overrides = @{flutter_webrtc = @{path = '.dart_tool/syncwatch_plugins/flutter_webrtc'}}}
$text = $marker + "`n" + ($settings | ConvertTo-Json -Depth 4) + "`n"
[IO.File]::WriteAllText($overridePath, $text, [Text.UTF8Encoding]::new($false))
Write-Host 'Prepared isolated WebRTC plugin. Run flutter pub get again before building.'
