name: Server CI

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

jobs:
  dart:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart format .
      - run: git diff --exit-code
      - run: dart analyze
